In [3]:
import pandas as pd
df = pd.read_csv('../../optData.csv')

In [4]:
display(df)

,date,act_symbol,expiration,strike,call_put,bid,ask,vol,delta,gamma,theta,vega,rho
0,2019-02-09,A,2019-02-15,65.0,Call,10.50,11.25,0.2705,1.0000,0.0000,-0.0046,0.0000,0.0124
1,2019-02-09,A,2019-02-15,65.0,Put,0.00,0.03,0.3133,-0.0002,0.0002,-0.0002,0.0001,0.0000
2,2019-02-09,A,2019-02-15,67.5,Call,8.15,8.50,0.2705,0.9991,0.0010,-0.0053,0.0003,0.0129
3,2019-02-09,A,2019-02-15,67.5,Put,0.00,0.03,0.3133,-0.0034,0.0031,-0.0024,0.0011,0.0000
4,2019-02-09,A,2019-02-15,70.0,Call,5.70,6.00,0.2705,0.9845,0.0137,-0.0127,0.0041,0.0132
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2019-02-09,AGN,2019-02-22,123.0,Put,0.56,0.85,0.3403,-0.1505,0.0268,-0.0720,0.0622,-0.0073
996,2019-02-09,AGN,2019-02-22,127.0,Call,5.70,6.20,0.3028,0.7702,0.0480,-0.1106,0.0781,0.0248
997,2019-02-09,AGN,2019-02-22,127.0,Put,1.19,1.36,0.2967,-0.2662,0.0433,-0.0875,0.0859,-0.0126
998,2019-02-09,AGN,2019-02-22,129.0,Call,4.25,4.80,0.2994,0.6664,0.0550,-0.1224,0.0913,0.0239
999,2019-02-09,AGN,2019-02-22,129.0,Put,1.74,1.94,0.2860,-0.3574,0.0511,-0.0954,0.0952,-0.0167